### ISSUE TITLE
아이디어 테스트

### ISSUE THREAD

**Issue by sigridjineth** [angelhackseoul/team-building#1]
# <아이디어 제목>

> 게시물에 적절한 Tag를 붙이는 것은 큰 도움이 됩니다. 고른 미션, 구하고자 하는 팀원의 역할을 달아주세요!

## 설명

아이디어 테스트

## 팀원을 구합니다!

디자이너 구합니다.

**Comment by yawol** [comment]
이거 만드실 분?

내 아이디어 쩐다궄ㅋㅋㅋㅋㅋ

**Comment by yawol** [comment]
저 개발도 못하고 아이디어도 없는데 받아주시나여? 그림도 못그림
