### ISSUE TITLE
[아이디어] <집에서 운동하기>

### ISSUE THREAD

**Issue by kimsuyeon0** [angelhackseoul/team-building#16]
# <집에서 운동하기>

## 설명

안녕하세요
코로나로 인해 사람이 많은 곳에서 운동을 하기 어려운 지금, 비대면 시대에 어울리는 운동은 역시 홈트입니다(하는 사람 많..죠?)
본 아이디어는 자세추정을 통해 집에서 운동을 하는 사람들에게 적절한 동기부여와 교정팁을 알려주는 서비스입니다.
제목이 <집에서 운동하기>인데 브랜딩과 상세기획을 통해 적절한 서비스 명칭을 붙일 예정입니다.

딥러닝 기반 프로젝트지만 모델만들기가 아니라 잘 가져다 쓰는 사람을 구합니다.(사전학습된 모델을 활용할 예정)
물론 갖다 쓴다해도 난관이 어느정도 있겠지만..^^ 그래도 열심히 할 분...찾습니다.

7일 안에 해야하기 때문에 서비스 MVP에 집중할 예정이며 마켓에 업로드할 생각이 있으신 분은 더 좋아요! (BM은 대략적으로 생각하였습니다)
물론 만약 더 좋은 아이디어가 있는 팀원분이 오신다면 급선회 가능합니다.

아마 주제픽은 커먼컴퓨터가 아닐까 싶어요!

## 팀원을 구합니다!

기왕하는거 잘하고 싶으신 분을 모십니다!
현재 기획1, 디자이너1, 개발자1(백엔드/서버)로 구성되어있습니다.
앱카메라로 라이브 영상 혹은 사진을 찍어야해서 앱 개발 가능하신 2분을 모십니다. 
TensorFlow Lite PoseNet을 사용하여 모바일에 내장할 예정입니다.
카카오 Pose api로 restapi사용할 수도 있습니다(다만 요건 사전 키를 받아야해서..)

**Comment by bluehope79** [comment]
박수여ㆍ / 개발자
자기소개
안녕하세요. 주로 자바 스프링으로 백엔드 개발을 하고 있으며, pythone / node.js 사용도 가능합니다.

관심사
우아한형제들 미션에 관심이 있는데 다 좋아요. 

사용 가능한 도구 / 기술
Java/Spring Boot 
Python3.6 /django
Node.js/Express.js

**Comment by kimsuyeon0** [comment]
.
